# Makefile.in generated by automake 1.11.5 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# $Id: Makefile.am 5797 2014-10-26 21:37:54Z flaterco $




am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/xtide
pkgincludedir = $(includedir)/xtide
pkglibdir = $(libdir)/xtide
pkglibexecdir = $(libexecdir)/xtide
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = tide$(EXEEXT) $(am__EXEEXT_1)
sbin_PROGRAMS = xttpd$(EXEEXT)
#am__append_1 = xtide
#am__append_2 = xtide.1
am__append_3 = libxtide/Dstr.cc
am__append_4 = libxtide/Dstr.hh
subdir = .
DIST_COMMON = README $(am__configure_deps) \
	$(am__nobase_include_HEADERS_DIST) $(dist_man_MANS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/configure \
	$(top_srcdir)/libxtide/autoconf-defines.h.in AUTHORS COPYING \
	ChangeLog INSTALL NEWS config.guess config.sub depcomp \
	install-sh ltmain.sh missing xml_l.cc xml_y.cc xml_y.h ylwrap
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/libxtide/autoconf-defines.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(sbindir)" "$(DESTDIR)$(man1dir)" \
	"$(DESTDIR)$(man8dir)" "$(DESTDIR)$(includedir)" \
	"$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libxtide_la_LIBADD =
am__libxtide_la_SOURCES_DIST = libxtide/Amplitude.cc libxtide/Angle.cc \
	libxtide/Banner.cc libxtide/Calendar.cc \
	libxtide/CalendarFormC.cc libxtide/CalendarFormH.cc \
	libxtide/CalendarFormL.cc libxtide/CalendarFormNotC.cc \
	libxtide/CalendarFormT.cc libxtide/ClientSideFont.cc \
	libxtide/Colors.cc libxtide/Constituent.cc \
	libxtide/ConstituentSet.cc libxtide/Coordinates.cc \
	libxtide/CurrentBearing.cc libxtide/Date.cc libxtide/Global.cc \
	libxtide/Graph.cc libxtide/HarmonicsFile.cc \
	libxtide/HarmonicsPath.cc libxtide/Interval.cc \
	libxtide/MetaField.cc libxtide/Nullable.cc \
	libxtide/NullableInterval.cc \
	libxtide/NullablePredictionValue.cc libxtide/Offsets.cc \
	libxtide/PixelatedGraph.cc libxtide/PredictionValue.cc \
	libxtide/RGBGraph.cc libxtide/Settings.cc libxtide/Skycal.cc \
	libxtide/Speed.cc libxtide/Station.cc libxtide/StationIndex.cc \
	libxtide/StationRef.cc libxtide/SubordinateStation.cc \
	libxtide/SVGGraph.cc libxtide/TTYGraph.cc \
	libxtide/TideEvent.cc libxtide/TideEventsOrganizer.cc \
	libxtide/Timestamp.cc libxtide/Units.cc libxtide/Year.cc \
	libxtide/xml_l.ll libxtide/xml_y.yy libxtide/Dstr.cc
am__objects_1 = Dstr.lo
am_libxtide_la_OBJECTS = Amplitude.lo Angle.lo Banner.lo Calendar.lo \
	CalendarFormC.lo CalendarFormH.lo CalendarFormL.lo \
	CalendarFormNotC.lo CalendarFormT.lo ClientSideFont.lo \
	Colors.lo Constituent.lo ConstituentSet.lo Coordinates.lo \
	CurrentBearing.lo Date.lo Global.lo Graph.lo HarmonicsFile.lo \
	HarmonicsPath.lo Interval.lo MetaField.lo Nullable.lo \
	NullableInterval.lo NullablePredictionValue.lo Offsets.lo \
	PixelatedGraph.lo PredictionValue.lo RGBGraph.lo Settings.lo \
	Skycal.lo Speed.lo Station.lo StationIndex.lo StationRef.lo \
	SubordinateStation.lo SVGGraph.lo TTYGraph.lo TideEvent.lo \
	TideEventsOrganizer.lo Timestamp.lo Units.lo Year.lo xml_l.lo \
	xml_y.lo $(am__objects_1)
libxtide_la_OBJECTS = $(am_libxtide_la_OBJECTS)
libxtide_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libxtide_la_LDFLAGS) $(LDFLAGS) -o $@
#am__EXEEXT_1 = xtide$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS) $(sbin_PROGRAMS)
am_tide_OBJECTS = tide.$(OBJEXT)
tide_OBJECTS = $(am_tide_OBJECTS)
tide_DEPENDENCIES = libxtide.la
am__xtide_SOURCES_DIST = errorExclaim.xpm.hh errorSunk.xpm.hh \
	icon_48x48_3color.xpm.hh wvsrtv.cc xtide.cc xtide.hh \
	xxAspect.cc xxAspect.hh xxClock.cc xxClock.hh xxDisclaimer.cc \
	xxDisclaimer.hh xxErrorBox.cc xxErrorBox.hh xxFilename.cc \
	xxFilename.hh xxGlobal.cc xxGlobal.hh xxGlobe.cc xxGlobe.hh \
	xxGraphMode.cc xxGraphMode.hh xxHelpBox.cc xxHelpBox.hh \
	xxHorizDialog.cc xxHorizDialog.hh xxLocationList.cc \
	xxLocationList.hh xxMap.cc xxMap.hh xxMarkLevel.cc \
	xxMarkLevel.hh xxMouseWheelViewport.cc xxMouseWheelViewport.hh \
	xxMultiChoice.cc xxMultiChoice.hh xxPixmapGraph.cc \
	xxPixmapGraph.hh xxPredictionWindow.cc xxPredictionWindow.hh \
	xxRareModeSavePrompts.cc xxRareModeSavePrompts.hh \
	xxReconfigurable.cc xxReconfigurable.hh xxRedrawable.cc \
	xxRedrawable.hh xxRoot.cc xxRoot.hh xxSimplePrompt.cc \
	xxSimplePrompt.hh xxStep.cc xxStep.hh xxTextMode.cc \
	xxTextMode.hh xxTimestamp.cc xxTimestamp.hh \
	xxTimestampDialog.cc xxTimestampDialog.hh xxUnsignedChooser.cc \
	xxUnsignedChooser.hh xxWidget.cc xxWidget.hh xxWindow.cc \
	xxWindow.hh xxX.cc xxX.hh
#am_xtide_OBJECTS = wvsrtv.$(OBJEXT) xtide.$(OBJEXT) \
#	xxAspect.$(OBJEXT) xxClock.$(OBJEXT) \
#	xxDisclaimer.$(OBJEXT) xxErrorBox.$(OBJEXT) \
#	xxFilename.$(OBJEXT) xxGlobal.$(OBJEXT) \
#	xxGlobe.$(OBJEXT) xxGraphMode.$(OBJEXT) \
#	xxHelpBox.$(OBJEXT) xxHorizDialog.$(OBJEXT) \
#	xxLocationList.$(OBJEXT) xxMap.$(OBJEXT) \
#	xxMarkLevel.$(OBJEXT) \
#	xxMouseWheelViewport.$(OBJEXT) \
#	xxMultiChoice.$(OBJEXT) xxPixmapGraph.$(OBJEXT) \
#	xxPredictionWindow.$(OBJEXT) \
#	xxRareModeSavePrompts.$(OBJEXT) \
#	xxReconfigurable.$(OBJEXT) xxRedrawable.$(OBJEXT) \
#	xxRoot.$(OBJEXT) xxSimplePrompt.$(OBJEXT) \
#	xxStep.$(OBJEXT) xxTextMode.$(OBJEXT) \
#	xxTimestamp.$(OBJEXT) xxTimestampDialog.$(OBJEXT) \
#	xxUnsignedChooser.$(OBJEXT) xxWidget.$(OBJEXT) \
#	xxWindow.$(OBJEXT) xxX.$(OBJEXT)
xtide_OBJECTS = $(am_xtide_OBJECTS)
#xtide_DEPENDENCIES = libxtide.la
xtide_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(xtide_LDFLAGS) $(LDFLAGS) -o $@
am_xttpd_OBJECTS = ZoneIndex.$(OBJEXT) xttpd.$(OBJEXT)
xttpd_OBJECTS = $(am_xttpd_OBJECTS)
xttpd_DEPENDENCIES = libxtide.la
DEFAULT_INCLUDES = -I. -I$(top_builddir)/libxtide
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
LEXCOMPILE = $(LEX) $(AM_LFLAGS) $(LFLAGS)
LTLEXCOMPILE = $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(LEX) $(AM_LFLAGS) $(LFLAGS)
YLWRAP = $(top_srcdir)/ylwrap
YACCCOMPILE = $(YACC) $(AM_YFLAGS) $(YFLAGS)
LTYACCCOMPILE = $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(YACC) $(AM_YFLAGS) $(YFLAGS)
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libxtide_la_SOURCES) $(tide_SOURCES) $(xtide_SOURCES) \
	$(xttpd_SOURCES)
DIST_SOURCES = $(am__libxtide_la_SOURCES_DIST) $(tide_SOURCES) \
	$(am__xtide_SOURCES_DIST) $(xttpd_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
man1dir = $(mandir)/man1
man8dir = $(mandir)/man8
NROFF = nroff
MANS = $(dist_man_MANS)
am__nobase_include_HEADERS_DIST = libxtide/Amplitude.hh \
	libxtide/Angle.hh libxtide/Banner.hh libxtide/BetterMap.hh \
	libxtide/Calendar.hh libxtide/CalendarFormC.hh \
	libxtide/CalendarFormH.hh libxtide/CalendarFormL.hh \
	libxtide/CalendarFormNotC.hh libxtide/CalendarFormT.hh \
	libxtide/ClientSideFont.hh libxtide/Colors.hh \
	libxtide/Configurable.hh libxtide/Constituent.hh \
	libxtide/ConstituentSet.hh libxtide/Coordinates.hh \
	libxtide/CurrentBearing.hh libxtide/Date.hh libxtide/Errors.hh \
	libxtide/Global.hh libxtide/Graph.hh libxtide/HarmonicsFile.hh \
	libxtide/HarmonicsPath.hh libxtide/Interval.hh \
	libxtide/MetaField.hh libxtide/ModeFormat.hh \
	libxtide/Nullable.hh libxtide/NullableInterval.hh \
	libxtide/NullablePredictionValue.hh libxtide/Offsets.hh \
	libxtide/PixelatedGraph.hh libxtide/PredictionValue.hh \
	libxtide/RGBGraph.hh libxtide/SafeVector.hh \
	libxtide/Settings.hh libxtide/Skycal.hh libxtide/Speed.hh \
	libxtide/Station.hh libxtide/StationIndex.hh \
	libxtide/StationRef.hh libxtide/SubordinateStation.hh \
	libxtide/SVGGraph.hh libxtide/TTYGraph.hh \
	libxtide/TideEvent.hh libxtide/TideEventsOrganizer.hh \
	libxtide/Timestamp.hh libxtide/Units.hh libxtide/Year.hh \
	libxtide/libxtide.hh libxtide/config.hh libxtide/rgb.hh \
	libxtide/xmlparser.hh libxtide/Dstr.hh
HEADERS = $(nobase_include_HEADERS) $(nobase_nodist_include_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/missing --run aclocal-1.11
ADDED_CPPFLAGS = 
ADDED_CXXFLAGS =  -std=gnu++0x
AMTAR = $${TAR-tar}
AR = ar
AUTOCONF = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/missing --run autoconf
AUTOHEADER = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/missing --run autoheader
AUTOMAKE = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/missing --run automake-1.11
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GPSD_LIBS = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LEX = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/missing --run flex
LEXLIB = 
LEX_OUTPUT_ROOT = 
LIBOBJS = 
LIBS = -ltcd -lpng -lz  -lm
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = xtide
PACKAGE_BUGREPORT = dave@flaterco.com
PACKAGE_NAME = XTide
PACKAGE_STRING = XTide 2.14
PACKAGE_TARNAME = xtide
PACKAGE_URL = 
PACKAGE_VERSION = 2.14
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 2.14
XAW = 
XMKMF = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS = 
X_PRE_LIBS = 
YACC = yacc
YFLAGS = 
abs_builddir = /home/rkitts/work/clubsoft/xtide/xtide-2.14
abs_srcdir = /home/rkitts/work/clubsoft/xtide/xtide-2.14
abs_top_builddir = /home/rkitts/work/clubsoft/xtide/xtide-2.14
abs_top_srcdir = /home/rkitts/work/clubsoft/xtide/xtide-2.14
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/rkitts/work/clubsoft/xtide/xtide-2.14/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
lib_LTLIBRARIES = libxtide.la
dist_man_MANS = tide.1 xttpd.8 $(am__append_2)
AM_CPPFLAGS = 
AM_CXXFLAGS =   -std=gnu++0x
BUILT_SOURCES = xml_y.h
AM_YFLAGS = -d
ACLOCAL_AMFLAGS = -I m4
CLEANFILES = INSTALL README ChangeLog NEWS AUTHORS README-QUICK
EXTRA_DIST = CONFIGURE-HELP CodingConventions.txt README-QUICK \
		  scripts/xtide.conf.sample \
		  scripts/Fedora/rc.xttpd \
		  scripts/Fedora/xttpd-wrapper.sh \
		  scripts/Fedora/xttpd.conf \
                  scripts/DOS/Makefile.dj2 \
                  scripts/DOS/.xtide.xml \
                  scripts/DOS/autoconf-defines.h \
                  scripts/VS/NOTES.txt \
                  scripts/VS/autoconf-defines.h \
                  scripts/VS/build.bat \
                  scripts/Android/build.sh \
		  iconsrc/Palette.ppm \
		  iconsrc/icon_16x16_3color.ico \
		  iconsrc/icon_16x16_3color.png \
		  iconsrc/icon_16x16_orig.png \
		  iconsrc/icon_48x48_3color.png \
		  iconsrc/icon_48x48_orig.png

libxtide_la_SOURCES = libxtide/Amplitude.cc libxtide/Angle.cc \
	libxtide/Banner.cc libxtide/Calendar.cc \
	libxtide/CalendarFormC.cc libxtide/CalendarFormH.cc \
	libxtide/CalendarFormL.cc libxtide/CalendarFormNotC.cc \
	libxtide/CalendarFormT.cc libxtide/ClientSideFont.cc \
	libxtide/Colors.cc libxtide/Constituent.cc \
	libxtide/ConstituentSet.cc libxtide/Coordinates.cc \
	libxtide/CurrentBearing.cc libxtide/Date.cc libxtide/Global.cc \
	libxtide/Graph.cc libxtide/HarmonicsFile.cc \
	libxtide/HarmonicsPath.cc libxtide/Interval.cc \
	libxtide/MetaField.cc libxtide/Nullable.cc \
	libxtide/NullableInterval.cc \
	libxtide/NullablePredictionValue.cc libxtide/Offsets.cc \
	libxtide/PixelatedGraph.cc libxtide/PredictionValue.cc \
	libxtide/RGBGraph.cc libxtide/Settings.cc libxtide/Skycal.cc \
	libxtide/Speed.cc libxtide/Station.cc libxtide/StationIndex.cc \
	libxtide/StationRef.cc libxtide/SubordinateStation.cc \
	libxtide/SVGGraph.cc libxtide/TTYGraph.cc \
	libxtide/TideEvent.cc libxtide/TideEventsOrganizer.cc \
	libxtide/Timestamp.cc libxtide/Units.cc libxtide/Year.cc \
	libxtide/xml_l.ll libxtide/xml_y.yy $(am__append_3)
nobase_include_HEADERS = libxtide/Amplitude.hh libxtide/Angle.hh \
	libxtide/Banner.hh libxtide/BetterMap.hh libxtide/Calendar.hh \
	libxtide/CalendarFormC.hh libxtide/CalendarFormH.hh \
	libxtide/CalendarFormL.hh libxtide/CalendarFormNotC.hh \
	libxtide/CalendarFormT.hh libxtide/ClientSideFont.hh \
	libxtide/Colors.hh libxtide/Configurable.hh \
	libxtide/Constituent.hh libxtide/ConstituentSet.hh \
	libxtide/Coordinates.hh libxtide/CurrentBearing.hh \
	libxtide/Date.hh libxtide/Errors.hh libxtide/Global.hh \
	libxtide/Graph.hh libxtide/HarmonicsFile.hh \
	libxtide/HarmonicsPath.hh libxtide/Interval.hh \
	libxtide/MetaField.hh libxtide/ModeFormat.hh \
	libxtide/Nullable.hh libxtide/NullableInterval.hh \
	libxtide/NullablePredictionValue.hh libxtide/Offsets.hh \
	libxtide/PixelatedGraph.hh libxtide/PredictionValue.hh \
	libxtide/RGBGraph.hh libxtide/SafeVector.hh \
	libxtide/Settings.hh libxtide/Skycal.hh libxtide/Speed.hh \
	libxtide/Station.hh libxtide/StationIndex.hh \
	libxtide/StationRef.hh libxtide/SubordinateStation.hh \
	libxtide/SVGGraph.hh libxtide/TTYGraph.hh \
	libxtide/TideEvent.hh libxtide/TideEventsOrganizer.hh \
	libxtide/Timestamp.hh libxtide/Units.hh libxtide/Year.hh \
	libxtide/libxtide.hh libxtide/config.hh libxtide/rgb.hh \
	libxtide/xmlparser.hh $(am__append_4)
nobase_nodist_include_HEADERS = libxtide/autoconf-defines.h

# -version-info current:revision:age

# Shared lib versions are almost, but not quite, completely unlike
# release versions.  They are sufficiently unlike that if the two
# happen to be the same it will cause people to jump to the conclusion
# that you don't know what you are doing.

# If the library source code has changed at all since the last update,
# then increment revision (c:r:a becomes c:r+1:a).

# If any interfaces have been added, removed, or changed since the
# last update, increment current, and set revision to 0.

# If any interfaces have been added since the last public release,
# then increment age.

# If any interfaces have been removed since the last public release,
# then set age to 0.

# FIXME: Update libtool version info on each release
libxtide_la_LDFLAGS = -version-info 0:0:0
#xtide_SOURCES = \
#  errorExclaim.xpm.hh errorSunk.xpm.hh icon_48x48_3color.xpm.hh          \
#  wvsrtv.cc xtide.cc xtide.hh xxAspect.cc xxAspect.hh xxClock.cc         \
#  xxClock.hh xxDisclaimer.cc xxDisclaimer.hh xxErrorBox.cc xxErrorBox.hh \
#  xxFilename.cc xxFilename.hh xxGlobal.cc xxGlobal.hh xxGlobe.cc         \
#  xxGlobe.hh xxGraphMode.cc xxGraphMode.hh xxHelpBox.cc xxHelpBox.hh     \
#  xxHorizDialog.cc xxHorizDialog.hh xxLocationList.cc xxLocationList.hh  \
#  xxMap.cc xxMap.hh xxMarkLevel.cc xxMarkLevel.hh                        \
#  xxMouseWheelViewport.cc xxMouseWheelViewport.hh xxMultiChoice.cc       \
#  xxMultiChoice.hh xxPixmapGraph.cc xxPixmapGraph.hh                     \
#  xxPredictionWindow.cc xxPredictionWindow.hh xxRareModeSavePrompts.cc   \
#  xxRareModeSavePrompts.hh xxReconfigurable.cc xxReconfigurable.hh       \
#  xxRedrawable.cc xxRedrawable.hh xxRoot.cc xxRoot.hh xxSimplePrompt.cc  \
#  xxSimplePrompt.hh xxStep.cc xxStep.hh xxTextMode.cc xxTextMode.hh      \
#  xxTimestamp.cc xxTimestamp.hh xxTimestampDialog.cc                     \
#  xxTimestampDialog.hh xxUnsignedChooser.cc xxUnsignedChooser.hh         \
#  xxWidget.cc xxWidget.hh xxWindow.cc xxWindow.hh xxX.cc xxX.hh

#xtide_LDFLAGS = 
#xtide_LDADD = libxtide.la  -l -lXmu -lXt -lSM -lICE -lXext -lX11 -lXpm 
tide_SOURCES = tide.cc
tide_LDADD = libxtide.la
xttpd_SOURCES = ZoneIndex.cc ZoneIndex.hh xttpd.cc
# xttpd needs -lsocket -lnsl on Solaris too.
xttpd_LDADD = libxtide.la 
all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cc .ll .lo .o .obj .yy
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

libxtide/autoconf-defines.h: libxtide/stamp-h1
	@if test ! -f $@; then rm -f libxtide/stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) libxtide/stamp-h1; else :; fi

libxtide/stamp-h1: $(top_srcdir)/libxtide/autoconf-defines.h.in $(top_builddir)/config.status
	@rm -f libxtide/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status libxtide/autoconf-defines.h
$(top_srcdir)/libxtide/autoconf-defines.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f libxtide/stamp-h1
	touch $@

distclean-hdr:
	-rm -f libxtide/autoconf-defines.h libxtide/stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
xml_y.h: xml_y.cc
	@if test ! -f $@; then rm -f xml_y.cc; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) xml_y.cc; else :; fi
libxtide.la: $(libxtide_la_OBJECTS) $(libxtide_la_DEPENDENCIES) $(EXTRA_libxtide_la_DEPENDENCIES) 
	$(libxtide_la_LINK) -rpath $(libdir) $(libxtide_la_OBJECTS) $(libxtide_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
install-sbinPROGRAMS: $(sbin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(sbin_PROGRAMS)'; test -n "$(sbindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(sbindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(sbindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(sbindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(sbindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-sbinPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(sbin_PROGRAMS)'; test -n "$(sbindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(sbindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(sbindir)" && rm -f $$files

clean-sbinPROGRAMS:
	@list='$(sbin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
tide$(EXEEXT): $(tide_OBJECTS) $(tide_DEPENDENCIES) $(EXTRA_tide_DEPENDENCIES) 
	@rm -f tide$(EXEEXT)
	$(CXXLINK) $(tide_OBJECTS) $(tide_LDADD) $(LIBS)
xtide$(EXEEXT): $(xtide_OBJECTS) $(xtide_DEPENDENCIES) $(EXTRA_xtide_DEPENDENCIES) 
	@rm -f xtide$(EXEEXT)
	$(xtide_LINK) $(xtide_OBJECTS) $(xtide_LDADD) $(LIBS)
xttpd$(EXEEXT): $(xttpd_OBJECTS) $(xttpd_DEPENDENCIES) $(EXTRA_xttpd_DEPENDENCIES) 
	@rm -f xttpd$(EXEEXT)
	$(CXXLINK) $(xttpd_OBJECTS) $(xttpd_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/Amplitude.Plo
include ./$(DEPDIR)/Angle.Plo
include ./$(DEPDIR)/Banner.Plo
include ./$(DEPDIR)/Calendar.Plo
include ./$(DEPDIR)/CalendarFormC.Plo
include ./$(DEPDIR)/CalendarFormH.Plo
include ./$(DEPDIR)/CalendarFormL.Plo
include ./$(DEPDIR)/CalendarFormNotC.Plo
include ./$(DEPDIR)/CalendarFormT.Plo
include ./$(DEPDIR)/ClientSideFont.Plo
include ./$(DEPDIR)/Colors.Plo
include ./$(DEPDIR)/Constituent.Plo
include ./$(DEPDIR)/ConstituentSet.Plo
include ./$(DEPDIR)/Coordinates.Plo
include ./$(DEPDIR)/CurrentBearing.Plo
include ./$(DEPDIR)/Date.Plo
include ./$(DEPDIR)/Dstr.Plo
include ./$(DEPDIR)/Global.Plo
include ./$(DEPDIR)/Graph.Plo
include ./$(DEPDIR)/HarmonicsFile.Plo
include ./$(DEPDIR)/HarmonicsPath.Plo
include ./$(DEPDIR)/Interval.Plo
include ./$(DEPDIR)/MetaField.Plo
include ./$(DEPDIR)/Nullable.Plo
include ./$(DEPDIR)/NullableInterval.Plo
include ./$(DEPDIR)/NullablePredictionValue.Plo
include ./$(DEPDIR)/Offsets.Plo
include ./$(DEPDIR)/PixelatedGraph.Plo
include ./$(DEPDIR)/PredictionValue.Plo
include ./$(DEPDIR)/RGBGraph.Plo
include ./$(DEPDIR)/SVGGraph.Plo
include ./$(DEPDIR)/Settings.Plo
include ./$(DEPDIR)/Skycal.Plo
include ./$(DEPDIR)/Speed.Plo
include ./$(DEPDIR)/Station.Plo
include ./$(DEPDIR)/StationIndex.Plo
include ./$(DEPDIR)/StationRef.Plo
include ./$(DEPDIR)/SubordinateStation.Plo
include ./$(DEPDIR)/TTYGraph.Plo
include ./$(DEPDIR)/TideEvent.Plo
include ./$(DEPDIR)/TideEventsOrganizer.Plo
include ./$(DEPDIR)/Timestamp.Plo
include ./$(DEPDIR)/Units.Plo
include ./$(DEPDIR)/Year.Plo
include ./$(DEPDIR)/ZoneIndex.Po
include ./$(DEPDIR)/tide.Po
include ./$(DEPDIR)/wvsrtv.Po
include ./$(DEPDIR)/xml_l.Plo
include ./$(DEPDIR)/xml_y.Plo
include ./$(DEPDIR)/xtide.Po
include ./$(DEPDIR)/xttpd.Po
include ./$(DEPDIR)/xxAspect.Po
include ./$(DEPDIR)/xxClock.Po
include ./$(DEPDIR)/xxDisclaimer.Po
include ./$(DEPDIR)/xxErrorBox.Po
include ./$(DEPDIR)/xxFilename.Po
include ./$(DEPDIR)/xxGlobal.Po
include ./$(DEPDIR)/xxGlobe.Po
include ./$(DEPDIR)/xxGraphMode.Po
include ./$(DEPDIR)/xxHelpBox.Po
include ./$(DEPDIR)/xxHorizDialog.Po
include ./$(DEPDIR)/xxLocationList.Po
include ./$(DEPDIR)/xxMap.Po
include ./$(DEPDIR)/xxMarkLevel.Po
include ./$(DEPDIR)/xxMouseWheelViewport.Po
include ./$(DEPDIR)/xxMultiChoice.Po
include ./$(DEPDIR)/xxPixmapGraph.Po
include ./$(DEPDIR)/xxPredictionWindow.Po
include ./$(DEPDIR)/xxRareModeSavePrompts.Po
include ./$(DEPDIR)/xxReconfigurable.Po
include ./$(DEPDIR)/xxRedrawable.Po
include ./$(DEPDIR)/xxRoot.Po
include ./$(DEPDIR)/xxSimplePrompt.Po
include ./$(DEPDIR)/xxStep.Po
include ./$(DEPDIR)/xxTextMode.Po
include ./$(DEPDIR)/xxTimestamp.Po
include ./$(DEPDIR)/xxTimestampDialog.Po
include ./$(DEPDIR)/xxUnsignedChooser.Po
include ./$(DEPDIR)/xxWidget.Po
include ./$(DEPDIR)/xxWindow.Po
include ./$(DEPDIR)/xxX.Po

.cc.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

Amplitude.lo: libxtide/Amplitude.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Amplitude.lo -MD -MP -MF $(DEPDIR)/Amplitude.Tpo -c -o Amplitude.lo `test -f 'libxtide/Amplitude.cc' || echo '$(srcdir)/'`libxtide/Amplitude.cc
	$(am__mv) $(DEPDIR)/Amplitude.Tpo $(DEPDIR)/Amplitude.Plo
#	source='libxtide/Amplitude.cc' object='Amplitude.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Amplitude.lo `test -f 'libxtide/Amplitude.cc' || echo '$(srcdir)/'`libxtide/Amplitude.cc

Angle.lo: libxtide/Angle.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Angle.lo -MD -MP -MF $(DEPDIR)/Angle.Tpo -c -o Angle.lo `test -f 'libxtide/Angle.cc' || echo '$(srcdir)/'`libxtide/Angle.cc
	$(am__mv) $(DEPDIR)/Angle.Tpo $(DEPDIR)/Angle.Plo
#	source='libxtide/Angle.cc' object='Angle.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Angle.lo `test -f 'libxtide/Angle.cc' || echo '$(srcdir)/'`libxtide/Angle.cc

Banner.lo: libxtide/Banner.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Banner.lo -MD -MP -MF $(DEPDIR)/Banner.Tpo -c -o Banner.lo `test -f 'libxtide/Banner.cc' || echo '$(srcdir)/'`libxtide/Banner.cc
	$(am__mv) $(DEPDIR)/Banner.Tpo $(DEPDIR)/Banner.Plo
#	source='libxtide/Banner.cc' object='Banner.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Banner.lo `test -f 'libxtide/Banner.cc' || echo '$(srcdir)/'`libxtide/Banner.cc

Calendar.lo: libxtide/Calendar.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Calendar.lo -MD -MP -MF $(DEPDIR)/Calendar.Tpo -c -o Calendar.lo `test -f 'libxtide/Calendar.cc' || echo '$(srcdir)/'`libxtide/Calendar.cc
	$(am__mv) $(DEPDIR)/Calendar.Tpo $(DEPDIR)/Calendar.Plo
#	source='libxtide/Calendar.cc' object='Calendar.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Calendar.lo `test -f 'libxtide/Calendar.cc' || echo '$(srcdir)/'`libxtide/Calendar.cc

CalendarFormC.lo: libxtide/CalendarFormC.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CalendarFormC.lo -MD -MP -MF $(DEPDIR)/CalendarFormC.Tpo -c -o CalendarFormC.lo `test -f 'libxtide/CalendarFormC.cc' || echo '$(srcdir)/'`libxtide/CalendarFormC.cc
	$(am__mv) $(DEPDIR)/CalendarFormC.Tpo $(DEPDIR)/CalendarFormC.Plo
#	source='libxtide/CalendarFormC.cc' object='CalendarFormC.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CalendarFormC.lo `test -f 'libxtide/CalendarFormC.cc' || echo '$(srcdir)/'`libxtide/CalendarFormC.cc

CalendarFormH.lo: libxtide/CalendarFormH.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CalendarFormH.lo -MD -MP -MF $(DEPDIR)/CalendarFormH.Tpo -c -o CalendarFormH.lo `test -f 'libxtide/CalendarFormH.cc' || echo '$(srcdir)/'`libxtide/CalendarFormH.cc
	$(am__mv) $(DEPDIR)/CalendarFormH.Tpo $(DEPDIR)/CalendarFormH.Plo
#	source='libxtide/CalendarFormH.cc' object='CalendarFormH.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CalendarFormH.lo `test -f 'libxtide/CalendarFormH.cc' || echo '$(srcdir)/'`libxtide/CalendarFormH.cc

CalendarFormL.lo: libxtide/CalendarFormL.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CalendarFormL.lo -MD -MP -MF $(DEPDIR)/CalendarFormL.Tpo -c -o CalendarFormL.lo `test -f 'libxtide/CalendarFormL.cc' || echo '$(srcdir)/'`libxtide/CalendarFormL.cc
	$(am__mv) $(DEPDIR)/CalendarFormL.Tpo $(DEPDIR)/CalendarFormL.Plo
#	source='libxtide/CalendarFormL.cc' object='CalendarFormL.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CalendarFormL.lo `test -f 'libxtide/CalendarFormL.cc' || echo '$(srcdir)/'`libxtide/CalendarFormL.cc

CalendarFormNotC.lo: libxtide/CalendarFormNotC.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CalendarFormNotC.lo -MD -MP -MF $(DEPDIR)/CalendarFormNotC.Tpo -c -o CalendarFormNotC.lo `test -f 'libxtide/CalendarFormNotC.cc' || echo '$(srcdir)/'`libxtide/CalendarFormNotC.cc
	$(am__mv) $(DEPDIR)/CalendarFormNotC.Tpo $(DEPDIR)/CalendarFormNotC.Plo
#	source='libxtide/CalendarFormNotC.cc' object='CalendarFormNotC.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CalendarFormNotC.lo `test -f 'libxtide/CalendarFormNotC.cc' || echo '$(srcdir)/'`libxtide/CalendarFormNotC.cc

CalendarFormT.lo: libxtide/CalendarFormT.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CalendarFormT.lo -MD -MP -MF $(DEPDIR)/CalendarFormT.Tpo -c -o CalendarFormT.lo `test -f 'libxtide/CalendarFormT.cc' || echo '$(srcdir)/'`libxtide/CalendarFormT.cc
	$(am__mv) $(DEPDIR)/CalendarFormT.Tpo $(DEPDIR)/CalendarFormT.Plo
#	source='libxtide/CalendarFormT.cc' object='CalendarFormT.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CalendarFormT.lo `test -f 'libxtide/CalendarFormT.cc' || echo '$(srcdir)/'`libxtide/CalendarFormT.cc

ClientSideFont.lo: libxtide/ClientSideFont.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ClientSideFont.lo -MD -MP -MF $(DEPDIR)/ClientSideFont.Tpo -c -o ClientSideFont.lo `test -f 'libxtide/ClientSideFont.cc' || echo '$(srcdir)/'`libxtide/ClientSideFont.cc
	$(am__mv) $(DEPDIR)/ClientSideFont.Tpo $(DEPDIR)/ClientSideFont.Plo
#	source='libxtide/ClientSideFont.cc' object='ClientSideFont.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ClientSideFont.lo `test -f 'libxtide/ClientSideFont.cc' || echo '$(srcdir)/'`libxtide/ClientSideFont.cc

Colors.lo: libxtide/Colors.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Colors.lo -MD -MP -MF $(DEPDIR)/Colors.Tpo -c -o Colors.lo `test -f 'libxtide/Colors.cc' || echo '$(srcdir)/'`libxtide/Colors.cc
	$(am__mv) $(DEPDIR)/Colors.Tpo $(DEPDIR)/Colors.Plo
#	source='libxtide/Colors.cc' object='Colors.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Colors.lo `test -f 'libxtide/Colors.cc' || echo '$(srcdir)/'`libxtide/Colors.cc

Constituent.lo: libxtide/Constituent.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Constituent.lo -MD -MP -MF $(DEPDIR)/Constituent.Tpo -c -o Constituent.lo `test -f 'libxtide/Constituent.cc' || echo '$(srcdir)/'`libxtide/Constituent.cc
	$(am__mv) $(DEPDIR)/Constituent.Tpo $(DEPDIR)/Constituent.Plo
#	source='libxtide/Constituent.cc' object='Constituent.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Constituent.lo `test -f 'libxtide/Constituent.cc' || echo '$(srcdir)/'`libxtide/Constituent.cc

ConstituentSet.lo: libxtide/ConstituentSet.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ConstituentSet.lo -MD -MP -MF $(DEPDIR)/ConstituentSet.Tpo -c -o ConstituentSet.lo `test -f 'libxtide/ConstituentSet.cc' || echo '$(srcdir)/'`libxtide/ConstituentSet.cc
	$(am__mv) $(DEPDIR)/ConstituentSet.Tpo $(DEPDIR)/ConstituentSet.Plo
#	source='libxtide/ConstituentSet.cc' object='ConstituentSet.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ConstituentSet.lo `test -f 'libxtide/ConstituentSet.cc' || echo '$(srcdir)/'`libxtide/ConstituentSet.cc

Coordinates.lo: libxtide/Coordinates.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Coordinates.lo -MD -MP -MF $(DEPDIR)/Coordinates.Tpo -c -o Coordinates.lo `test -f 'libxtide/Coordinates.cc' || echo '$(srcdir)/'`libxtide/Coordinates.cc
	$(am__mv) $(DEPDIR)/Coordinates.Tpo $(DEPDIR)/Coordinates.Plo
#	source='libxtide/Coordinates.cc' object='Coordinates.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Coordinates.lo `test -f 'libxtide/Coordinates.cc' || echo '$(srcdir)/'`libxtide/Coordinates.cc

CurrentBearing.lo: libxtide/CurrentBearing.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT CurrentBearing.lo -MD -MP -MF $(DEPDIR)/CurrentBearing.Tpo -c -o CurrentBearing.lo `test -f 'libxtide/CurrentBearing.cc' || echo '$(srcdir)/'`libxtide/CurrentBearing.cc
	$(am__mv) $(DEPDIR)/CurrentBearing.Tpo $(DEPDIR)/CurrentBearing.Plo
#	source='libxtide/CurrentBearing.cc' object='CurrentBearing.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o CurrentBearing.lo `test -f 'libxtide/CurrentBearing.cc' || echo '$(srcdir)/'`libxtide/CurrentBearing.cc

Date.lo: libxtide/Date.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Date.lo -MD -MP -MF $(DEPDIR)/Date.Tpo -c -o Date.lo `test -f 'libxtide/Date.cc' || echo '$(srcdir)/'`libxtide/Date.cc
	$(am__mv) $(DEPDIR)/Date.Tpo $(DEPDIR)/Date.Plo
#	source='libxtide/Date.cc' object='Date.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Date.lo `test -f 'libxtide/Date.cc' || echo '$(srcdir)/'`libxtide/Date.cc

Global.lo: libxtide/Global.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Global.lo -MD -MP -MF $(DEPDIR)/Global.Tpo -c -o Global.lo `test -f 'libxtide/Global.cc' || echo '$(srcdir)/'`libxtide/Global.cc
	$(am__mv) $(DEPDIR)/Global.Tpo $(DEPDIR)/Global.Plo
#	source='libxtide/Global.cc' object='Global.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Global.lo `test -f 'libxtide/Global.cc' || echo '$(srcdir)/'`libxtide/Global.cc

Graph.lo: libxtide/Graph.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Graph.lo -MD -MP -MF $(DEPDIR)/Graph.Tpo -c -o Graph.lo `test -f 'libxtide/Graph.cc' || echo '$(srcdir)/'`libxtide/Graph.cc
	$(am__mv) $(DEPDIR)/Graph.Tpo $(DEPDIR)/Graph.Plo
#	source='libxtide/Graph.cc' object='Graph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Graph.lo `test -f 'libxtide/Graph.cc' || echo '$(srcdir)/'`libxtide/Graph.cc

HarmonicsFile.lo: libxtide/HarmonicsFile.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HarmonicsFile.lo -MD -MP -MF $(DEPDIR)/HarmonicsFile.Tpo -c -o HarmonicsFile.lo `test -f 'libxtide/HarmonicsFile.cc' || echo '$(srcdir)/'`libxtide/HarmonicsFile.cc
	$(am__mv) $(DEPDIR)/HarmonicsFile.Tpo $(DEPDIR)/HarmonicsFile.Plo
#	source='libxtide/HarmonicsFile.cc' object='HarmonicsFile.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HarmonicsFile.lo `test -f 'libxtide/HarmonicsFile.cc' || echo '$(srcdir)/'`libxtide/HarmonicsFile.cc

HarmonicsPath.lo: libxtide/HarmonicsPath.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HarmonicsPath.lo -MD -MP -MF $(DEPDIR)/HarmonicsPath.Tpo -c -o HarmonicsPath.lo `test -f 'libxtide/HarmonicsPath.cc' || echo '$(srcdir)/'`libxtide/HarmonicsPath.cc
	$(am__mv) $(DEPDIR)/HarmonicsPath.Tpo $(DEPDIR)/HarmonicsPath.Plo
#	source='libxtide/HarmonicsPath.cc' object='HarmonicsPath.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HarmonicsPath.lo `test -f 'libxtide/HarmonicsPath.cc' || echo '$(srcdir)/'`libxtide/HarmonicsPath.cc

Interval.lo: libxtide/Interval.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Interval.lo -MD -MP -MF $(DEPDIR)/Interval.Tpo -c -o Interval.lo `test -f 'libxtide/Interval.cc' || echo '$(srcdir)/'`libxtide/Interval.cc
	$(am__mv) $(DEPDIR)/Interval.Tpo $(DEPDIR)/Interval.Plo
#	source='libxtide/Interval.cc' object='Interval.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Interval.lo `test -f 'libxtide/Interval.cc' || echo '$(srcdir)/'`libxtide/Interval.cc

MetaField.lo: libxtide/MetaField.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT MetaField.lo -MD -MP -MF $(DEPDIR)/MetaField.Tpo -c -o MetaField.lo `test -f 'libxtide/MetaField.cc' || echo '$(srcdir)/'`libxtide/MetaField.cc
	$(am__mv) $(DEPDIR)/MetaField.Tpo $(DEPDIR)/MetaField.Plo
#	source='libxtide/MetaField.cc' object='MetaField.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MetaField.lo `test -f 'libxtide/MetaField.cc' || echo '$(srcdir)/'`libxtide/MetaField.cc

Nullable.lo: libxtide/Nullable.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Nullable.lo -MD -MP -MF $(DEPDIR)/Nullable.Tpo -c -o Nullable.lo `test -f 'libxtide/Nullable.cc' || echo '$(srcdir)/'`libxtide/Nullable.cc
	$(am__mv) $(DEPDIR)/Nullable.Tpo $(DEPDIR)/Nullable.Plo
#	source='libxtide/Nullable.cc' object='Nullable.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Nullable.lo `test -f 'libxtide/Nullable.cc' || echo '$(srcdir)/'`libxtide/Nullable.cc

NullableInterval.lo: libxtide/NullableInterval.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT NullableInterval.lo -MD -MP -MF $(DEPDIR)/NullableInterval.Tpo -c -o NullableInterval.lo `test -f 'libxtide/NullableInterval.cc' || echo '$(srcdir)/'`libxtide/NullableInterval.cc
	$(am__mv) $(DEPDIR)/NullableInterval.Tpo $(DEPDIR)/NullableInterval.Plo
#	source='libxtide/NullableInterval.cc' object='NullableInterval.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o NullableInterval.lo `test -f 'libxtide/NullableInterval.cc' || echo '$(srcdir)/'`libxtide/NullableInterval.cc

NullablePredictionValue.lo: libxtide/NullablePredictionValue.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT NullablePredictionValue.lo -MD -MP -MF $(DEPDIR)/NullablePredictionValue.Tpo -c -o NullablePredictionValue.lo `test -f 'libxtide/NullablePredictionValue.cc' || echo '$(srcdir)/'`libxtide/NullablePredictionValue.cc
	$(am__mv) $(DEPDIR)/NullablePredictionValue.Tpo $(DEPDIR)/NullablePredictionValue.Plo
#	source='libxtide/NullablePredictionValue.cc' object='NullablePredictionValue.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o NullablePredictionValue.lo `test -f 'libxtide/NullablePredictionValue.cc' || echo '$(srcdir)/'`libxtide/NullablePredictionValue.cc

Offsets.lo: libxtide/Offsets.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Offsets.lo -MD -MP -MF $(DEPDIR)/Offsets.Tpo -c -o Offsets.lo `test -f 'libxtide/Offsets.cc' || echo '$(srcdir)/'`libxtide/Offsets.cc
	$(am__mv) $(DEPDIR)/Offsets.Tpo $(DEPDIR)/Offsets.Plo
#	source='libxtide/Offsets.cc' object='Offsets.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Offsets.lo `test -f 'libxtide/Offsets.cc' || echo '$(srcdir)/'`libxtide/Offsets.cc

PixelatedGraph.lo: libxtide/PixelatedGraph.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PixelatedGraph.lo -MD -MP -MF $(DEPDIR)/PixelatedGraph.Tpo -c -o PixelatedGraph.lo `test -f 'libxtide/PixelatedGraph.cc' || echo '$(srcdir)/'`libxtide/PixelatedGraph.cc
	$(am__mv) $(DEPDIR)/PixelatedGraph.Tpo $(DEPDIR)/PixelatedGraph.Plo
#	source='libxtide/PixelatedGraph.cc' object='PixelatedGraph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PixelatedGraph.lo `test -f 'libxtide/PixelatedGraph.cc' || echo '$(srcdir)/'`libxtide/PixelatedGraph.cc

PredictionValue.lo: libxtide/PredictionValue.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PredictionValue.lo -MD -MP -MF $(DEPDIR)/PredictionValue.Tpo -c -o PredictionValue.lo `test -f 'libxtide/PredictionValue.cc' || echo '$(srcdir)/'`libxtide/PredictionValue.cc
	$(am__mv) $(DEPDIR)/PredictionValue.Tpo $(DEPDIR)/PredictionValue.Plo
#	source='libxtide/PredictionValue.cc' object='PredictionValue.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PredictionValue.lo `test -f 'libxtide/PredictionValue.cc' || echo '$(srcdir)/'`libxtide/PredictionValue.cc

RGBGraph.lo: libxtide/RGBGraph.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RGBGraph.lo -MD -MP -MF $(DEPDIR)/RGBGraph.Tpo -c -o RGBGraph.lo `test -f 'libxtide/RGBGraph.cc' || echo '$(srcdir)/'`libxtide/RGBGraph.cc
	$(am__mv) $(DEPDIR)/RGBGraph.Tpo $(DEPDIR)/RGBGraph.Plo
#	source='libxtide/RGBGraph.cc' object='RGBGraph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RGBGraph.lo `test -f 'libxtide/RGBGraph.cc' || echo '$(srcdir)/'`libxtide/RGBGraph.cc

Settings.lo: libxtide/Settings.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Settings.lo -MD -MP -MF $(DEPDIR)/Settings.Tpo -c -o Settings.lo `test -f 'libxtide/Settings.cc' || echo '$(srcdir)/'`libxtide/Settings.cc
	$(am__mv) $(DEPDIR)/Settings.Tpo $(DEPDIR)/Settings.Plo
#	source='libxtide/Settings.cc' object='Settings.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Settings.lo `test -f 'libxtide/Settings.cc' || echo '$(srcdir)/'`libxtide/Settings.cc

Skycal.lo: libxtide/Skycal.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Skycal.lo -MD -MP -MF $(DEPDIR)/Skycal.Tpo -c -o Skycal.lo `test -f 'libxtide/Skycal.cc' || echo '$(srcdir)/'`libxtide/Skycal.cc
	$(am__mv) $(DEPDIR)/Skycal.Tpo $(DEPDIR)/Skycal.Plo
#	source='libxtide/Skycal.cc' object='Skycal.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Skycal.lo `test -f 'libxtide/Skycal.cc' || echo '$(srcdir)/'`libxtide/Skycal.cc

Speed.lo: libxtide/Speed.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Speed.lo -MD -MP -MF $(DEPDIR)/Speed.Tpo -c -o Speed.lo `test -f 'libxtide/Speed.cc' || echo '$(srcdir)/'`libxtide/Speed.cc
	$(am__mv) $(DEPDIR)/Speed.Tpo $(DEPDIR)/Speed.Plo
#	source='libxtide/Speed.cc' object='Speed.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Speed.lo `test -f 'libxtide/Speed.cc' || echo '$(srcdir)/'`libxtide/Speed.cc

Station.lo: libxtide/Station.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Station.lo -MD -MP -MF $(DEPDIR)/Station.Tpo -c -o Station.lo `test -f 'libxtide/Station.cc' || echo '$(srcdir)/'`libxtide/Station.cc
	$(am__mv) $(DEPDIR)/Station.Tpo $(DEPDIR)/Station.Plo
#	source='libxtide/Station.cc' object='Station.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Station.lo `test -f 'libxtide/Station.cc' || echo '$(srcdir)/'`libxtide/Station.cc

StationIndex.lo: libxtide/StationIndex.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT StationIndex.lo -MD -MP -MF $(DEPDIR)/StationIndex.Tpo -c -o StationIndex.lo `test -f 'libxtide/StationIndex.cc' || echo '$(srcdir)/'`libxtide/StationIndex.cc
	$(am__mv) $(DEPDIR)/StationIndex.Tpo $(DEPDIR)/StationIndex.Plo
#	source='libxtide/StationIndex.cc' object='StationIndex.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o StationIndex.lo `test -f 'libxtide/StationIndex.cc' || echo '$(srcdir)/'`libxtide/StationIndex.cc

StationRef.lo: libxtide/StationRef.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT StationRef.lo -MD -MP -MF $(DEPDIR)/StationRef.Tpo -c -o StationRef.lo `test -f 'libxtide/StationRef.cc' || echo '$(srcdir)/'`libxtide/StationRef.cc
	$(am__mv) $(DEPDIR)/StationRef.Tpo $(DEPDIR)/StationRef.Plo
#	source='libxtide/StationRef.cc' object='StationRef.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o StationRef.lo `test -f 'libxtide/StationRef.cc' || echo '$(srcdir)/'`libxtide/StationRef.cc

SubordinateStation.lo: libxtide/SubordinateStation.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT SubordinateStation.lo -MD -MP -MF $(DEPDIR)/SubordinateStation.Tpo -c -o SubordinateStation.lo `test -f 'libxtide/SubordinateStation.cc' || echo '$(srcdir)/'`libxtide/SubordinateStation.cc
	$(am__mv) $(DEPDIR)/SubordinateStation.Tpo $(DEPDIR)/SubordinateStation.Plo
#	source='libxtide/SubordinateStation.cc' object='SubordinateStation.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o SubordinateStation.lo `test -f 'libxtide/SubordinateStation.cc' || echo '$(srcdir)/'`libxtide/SubordinateStation.cc

SVGGraph.lo: libxtide/SVGGraph.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT SVGGraph.lo -MD -MP -MF $(DEPDIR)/SVGGraph.Tpo -c -o SVGGraph.lo `test -f 'libxtide/SVGGraph.cc' || echo '$(srcdir)/'`libxtide/SVGGraph.cc
	$(am__mv) $(DEPDIR)/SVGGraph.Tpo $(DEPDIR)/SVGGraph.Plo
#	source='libxtide/SVGGraph.cc' object='SVGGraph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o SVGGraph.lo `test -f 'libxtide/SVGGraph.cc' || echo '$(srcdir)/'`libxtide/SVGGraph.cc

TTYGraph.lo: libxtide/TTYGraph.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TTYGraph.lo -MD -MP -MF $(DEPDIR)/TTYGraph.Tpo -c -o TTYGraph.lo `test -f 'libxtide/TTYGraph.cc' || echo '$(srcdir)/'`libxtide/TTYGraph.cc
	$(am__mv) $(DEPDIR)/TTYGraph.Tpo $(DEPDIR)/TTYGraph.Plo
#	source='libxtide/TTYGraph.cc' object='TTYGraph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TTYGraph.lo `test -f 'libxtide/TTYGraph.cc' || echo '$(srcdir)/'`libxtide/TTYGraph.cc

TideEvent.lo: libxtide/TideEvent.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TideEvent.lo -MD -MP -MF $(DEPDIR)/TideEvent.Tpo -c -o TideEvent.lo `test -f 'libxtide/TideEvent.cc' || echo '$(srcdir)/'`libxtide/TideEvent.cc
	$(am__mv) $(DEPDIR)/TideEvent.Tpo $(DEPDIR)/TideEvent.Plo
#	source='libxtide/TideEvent.cc' object='TideEvent.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TideEvent.lo `test -f 'libxtide/TideEvent.cc' || echo '$(srcdir)/'`libxtide/TideEvent.cc

TideEventsOrganizer.lo: libxtide/TideEventsOrganizer.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TideEventsOrganizer.lo -MD -MP -MF $(DEPDIR)/TideEventsOrganizer.Tpo -c -o TideEventsOrganizer.lo `test -f 'libxtide/TideEventsOrganizer.cc' || echo '$(srcdir)/'`libxtide/TideEventsOrganizer.cc
	$(am__mv) $(DEPDIR)/TideEventsOrganizer.Tpo $(DEPDIR)/TideEventsOrganizer.Plo
#	source='libxtide/TideEventsOrganizer.cc' object='TideEventsOrganizer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TideEventsOrganizer.lo `test -f 'libxtide/TideEventsOrganizer.cc' || echo '$(srcdir)/'`libxtide/TideEventsOrganizer.cc

Timestamp.lo: libxtide/Timestamp.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Timestamp.lo -MD -MP -MF $(DEPDIR)/Timestamp.Tpo -c -o Timestamp.lo `test -f 'libxtide/Timestamp.cc' || echo '$(srcdir)/'`libxtide/Timestamp.cc
	$(am__mv) $(DEPDIR)/Timestamp.Tpo $(DEPDIR)/Timestamp.Plo
#	source='libxtide/Timestamp.cc' object='Timestamp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Timestamp.lo `test -f 'libxtide/Timestamp.cc' || echo '$(srcdir)/'`libxtide/Timestamp.cc

Units.lo: libxtide/Units.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Units.lo -MD -MP -MF $(DEPDIR)/Units.Tpo -c -o Units.lo `test -f 'libxtide/Units.cc' || echo '$(srcdir)/'`libxtide/Units.cc
	$(am__mv) $(DEPDIR)/Units.Tpo $(DEPDIR)/Units.Plo
#	source='libxtide/Units.cc' object='Units.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Units.lo `test -f 'libxtide/Units.cc' || echo '$(srcdir)/'`libxtide/Units.cc

Year.lo: libxtide/Year.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Year.lo -MD -MP -MF $(DEPDIR)/Year.Tpo -c -o Year.lo `test -f 'libxtide/Year.cc' || echo '$(srcdir)/'`libxtide/Year.cc
	$(am__mv) $(DEPDIR)/Year.Tpo $(DEPDIR)/Year.Plo
#	source='libxtide/Year.cc' object='Year.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Year.lo `test -f 'libxtide/Year.cc' || echo '$(srcdir)/'`libxtide/Year.cc

Dstr.lo: libxtide/Dstr.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Dstr.lo -MD -MP -MF $(DEPDIR)/Dstr.Tpo -c -o Dstr.lo `test -f 'libxtide/Dstr.cc' || echo '$(srcdir)/'`libxtide/Dstr.cc
	$(am__mv) $(DEPDIR)/Dstr.Tpo $(DEPDIR)/Dstr.Plo
#	source='libxtide/Dstr.cc' object='Dstr.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Dstr.lo `test -f 'libxtide/Dstr.cc' || echo '$(srcdir)/'`libxtide/Dstr.cc

.ll.cc:
	$(am__skiplex) $(SHELL) $(YLWRAP) $< $(LEX_OUTPUT_ROOT).c $@ -- $(LEXCOMPILE)

xml_l.cc: libxtide/xml_l.ll
	 \
	$(am__skiplex) \
	$(SHELL) $(YLWRAP) `test -f 'libxtide/xml_l.ll' || echo '$(srcdir)/'`libxtide/xml_l.ll $(LEX_OUTPUT_ROOT).c xml_l.cc -- $(LEX) $(AM_LFLAGS) $(LFLAGS)

.yy.cc:
	$(am__skipyacc) $(SHELL) $(YLWRAP) $< y.tab.c $@ y.tab.h $*.h y.output $*.output -- $(YACCCOMPILE)

xml_y.cc: libxtide/xml_y.yy
	 \
	$(am__skipyacc) \
	$(SHELL) $(YLWRAP) `test -f 'libxtide/xml_y.yy' || echo '$(srcdir)/'`libxtide/xml_y.yy y.tab.c xml_y.cc y.tab.h xml_y.h y.output xml_y.output -- $(YACC) $(AM_YFLAGS) $(YFLAGS)

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-man1: $(dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(dist_man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)
install-man8: $(dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(dist_man_MANS)'; \
	test -n "$(man8dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man8dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man8dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.8[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^8][0-9a-z]*$$,8,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man8dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man8dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man8dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man8dir)" || exit $$?; }; \
	done; }

uninstall-man8:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man8dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.8[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^8][0-9a-z]*$$,8,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man8dir)'; $(am__uninstall_files_from_dir)
install-nobase_includeHEADERS: $(nobase_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)
install-nobase_nodist_includeHEADERS: $(nobase_nodist_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_nodist_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_nodist_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_nodist_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@list='$(MANS)'; if test -n "$$list"; then \
	  list=`for p in $$list; do \
	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
	  if test -n "$$list" && \
	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
	    exit 1; \
	  else :; fi; \
	else :; fi
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(MANS) $(HEADERS)
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(man8dir)" "$(DESTDIR)$(includedir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-rm -f xml_l.cc
	-rm -f xml_y.cc
	-rm -f xml_y.h
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-sbinPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-man install-nobase_includeHEADERS \
	install-nobase_nodist_includeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES \
	install-sbinPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1 install-man8

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-man uninstall-nobase_includeHEADERS \
	uninstall-nobase_nodist_includeHEADERS uninstall-sbinPROGRAMS

uninstall-man: uninstall-man1 uninstall-man8

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-sbinPROGRAMS ctags dist dist-all \
	dist-bzip2 dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-man1 install-man8 \
	install-nobase_includeHEADERS \
	install-nobase_nodist_includeHEADERS install-pdf \
	install-pdf-am install-ps install-ps-am install-sbinPROGRAMS \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-libLTLIBRARIES uninstall-man \
	uninstall-man1 uninstall-man8 uninstall-nobase_includeHEADERS \
	uninstall-nobase_nodist_includeHEADERS uninstall-sbinPROGRAMS


# Unsolved problem:
# When building from scratch with no xml_l.cc xml_y.cc xml_y.h, it often
# forgets to create xml_y.h before trying to compile xml_l.cc.  Why???

xmlclean:
	rm -f xml_l.cc xml_y.cc xml_y.h

docs:   INSTALL README ChangeLog NEWS AUTHORS README-QUICK
.PHONY: INSTALL README ChangeLog NEWS AUTHORS README-QUICK docs

# "Generic" INSTALL moved to CONFIGURE-HELP so that something more helpful
# can go here.
INSTALL:
	lynx -dump "http://www.flaterco.com/xtide/installation.html" > INSTALL

README:
	lynx -dump "http://www.flaterco.com/xtide/xtide.html" > README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/disclaimer.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/introduction.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/sysreq.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/installation.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/ports.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/modes.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/interactive.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/advanced.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/tty.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/xttpd.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/settings.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/harmonics.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/bugs.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/faq.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/design.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/bibliography.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/time_t.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/mincurrents.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/pound_to_fit.html" >> README
	echo "" >> README
	echo "################################################################" >> README
	echo "" >> README
	lynx -dump "http://www.flaterco.com/xtide/xtide1diff.html" >> README
	echo "" >> README

ChangeLog:
	lynx -dump "http://www.flaterco.com/xtide/changelog.html" > ChangeLog

NEWS:
	lynx -dump "http://www.flaterco.com/xtide/news.html" > NEWS

AUTHORS:
	lynx -dump "http://www.flaterco.com/xtide/credits.html" > AUTHORS

README-QUICK:
	lynx -dump "http://www.flaterco.com/xtide/quickinst.html" > README-QUICK

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
